import { Link } from 'react-router-dom';

const updated = 'August 21, 2026';

export function PrivacyPolicyPage() { return <LegalPage title="Privacy Policy"><p>WhatstheUp, operated by Tech Pearl Solutions, provides software for businesses to manage consented contacts and send approved WhatsApp communications through Meta's official WhatsApp Business Platform.</p><h2>Information we process</h2><p>We process account details, business workspace information, contact information uploaded by customers, consent records, WhatsApp Business account identifiers, message templates, campaign activity, delivery events, and technical security logs. We do not ask for or store your Meta password.</p><h2>How information is used</h2><p>Information is used to provide and secure the service, connect customer-owned Meta assets, send requested communications, display delivery results, prevent abuse, provide support, and comply with legal obligations. We do not sell personal information.</p><h2>Sharing and processors</h2><p>Information is shared only as needed with service providers that operate the product, including Meta/WhatsApp for messaging, hosting and infrastructure providers, and email delivery providers. Customers are responsible for obtaining valid recipient consent and following WhatsApp policies and applicable law.</p><h2>Retention and security</h2><p>We retain information while an account is active and as reasonably required for security, support, contractual, and legal purposes. We use access controls, encryption for sensitive platform tokens, audit logging, and secure transport. No internet service can guarantee absolute security.</p><h2>Your choices</h2><p>You may request access, correction, export, or deletion of your account information. Business message recipients should contact the business that sent the message or opt out through the method it provides.</p><h2>Contact</h2><p>For privacy questions, email <a href="mailto:superadmin@whatsdup.in">superadmin@whatsdup.in</a>.</p></LegalPage>; }

export function TermsPage() { return <LegalPage title="Terms of Service"><p>By using WhatstheUp, you agree to use the service lawfully and only for communications recipients have agreed to receive.</p><h2>Customer responsibilities</h2><p>You are responsible for your account, uploaded data, recipient consent, message content, templates, and compliance with Meta's WhatsApp Business terms, commerce and messaging policies, and applicable laws. Spam, deceptive content, unlawful content, credential sharing, and attempts to bypass platform safeguards are prohibited.</p><h2>Third-party services</h2><p>The service depends on Meta, WhatsApp, hosting, and other providers. Their approvals, availability, pricing, limits, and policies are outside our control. Connecting a Meta account authorizes WhatstheUp to operate the selected WhatsApp assets for the requested service functions.</p><h2>Availability and liability</h2><p>We work to provide a secure and reliable service, but availability is not guaranteed. To the extent permitted by law, WhatstheUp is provided without implied warranties and Tech Pearl Solutions is not liable for indirect or consequential losses.</p><h2>Suspension and termination</h2><p>We may restrict accounts that create security, legal, payment, or platform-policy risk. You may stop using the service and request account deletion at any time.</p><h2>Contact</h2><p>Questions may be sent to <a href="mailto:superadmin@whatsdup.in">superadmin@whatsdup.in</a>.</p></LegalPage>; }

export function DataDeletionPage() { return <LegalPage title="User Data Deletion"><p>You can request deletion of your WhatstheUp account and associated personal information by emailing <a href="mailto:superadmin@whatsdup.in?subject=WhatstheUp%20data%20deletion%20request">superadmin@whatsdup.in</a> from the email address registered to your account.</p><h2>Include in your request</h2><p>Provide your registered email address, business workspace name, and the words “Data deletion request.” We may ask you to verify account ownership before processing the request.</p><h2>What happens next</h2><p>We will disconnect linked Meta assets and delete or anonymize account information that is not required for security, fraud prevention, contractual, or legal recordkeeping. We aim to acknowledge requests within 7 days and complete verified requests within 30 days, subject to applicable law.</p><h2>Meta permissions</h2><p>You may also remove WhatstheUp from your Facebook Business Integrations or Meta Business settings. Removing the integration stops future access but does not by itself delete information already stored in your WhatstheUp workspace; use the request process above for deletion.</p></LegalPage>; }

function LegalPage({ title, children }: { title: string; children: React.ReactNode }) { return <main className="min-h-screen bg-canvas px-5 py-12"><article className="mx-auto max-w-3xl rounded-3xl border border-line bg-white p-7 shadow-card sm:p-12"><Link to="/login" className="text-sm font-semibold text-brand-700">WhatstheUp</Link><h1 className="mt-6 text-4xl font-semibold tracking-tight">{title}</h1><p className="mt-2 text-sm text-muted">Last updated: {updated}</p><div className="mt-8 space-y-5 leading-7 text-ink [&_a]:text-brand-700 [&_h2]:pt-3 [&_h2]:text-xl [&_h2]:font-semibold">{children}</div></article></main>; }
