import type { Metadata } from "next";
import { LegalPage } from "../site-components";
export const metadata: Metadata = { title: "Privacy Policy | WhatstheUp", description: "How WhatstheUp collects, uses and protects personal information." };
export default function Privacy() { return <LegalPage eyebrow="Privacy" title="Privacy Policy" intro="This policy explains how WhatstheUp handles account, contact and messaging data when businesses use our services.">
  <h2>1. Who this policy covers</h2><p>This policy applies to visitors to whatstheup.in and users of the WhatstheUp business messaging platform. A customer business is generally the controller of its uploaded contacts and campaign content; WhatstheUp processes that information to provide the service.</p>
  <h2>2. Information we collect</h2><p>We may collect account and business details, authentication and session information, support communications, opted-in contact records uploaded by customers, campaign configuration, template details, delivery events, audit logs and technical information such as IP address, browser and device information.</p>
  <h2>3. How we use information</h2><p>We use information to authenticate users, provide tenant-isolated workspaces, connect approved Meta assets, process campaigns, maintain consent and suppression records, report message outcomes, protect the service, troubleshoot failures and comply with applicable law.</p>
  <h2>4. WhatsApp and Meta</h2><p>WhatstheUp uses the official WhatsApp Business Platform Cloud API. When a customer connects Meta assets or sends messages, relevant information is processed by Meta under its applicable terms and privacy policies. WhatstheUp does not request or store a customer’s Meta password.</p>
  <h2>5. Sharing and service providers</h2><p>We disclose information only as needed to operate the service, including hosting, email, storage and the official Meta/WhatsApp platform, or when required by law. We do not sell personal information.</p>
  <h2>6. Retention and security</h2><p>We retain information for the period needed to provide the service, meet contractual and legal obligations, resolve disputes and maintain security records. Controls include encryption for stored platform credentials, server-side authorization, tenant isolation, session revocation, audit logging and protected storage.</p>
  <h2>7. Your choices and rights</h2><p>Depending on applicable law, individuals may request access, correction or deletion. Message recipients should first contact the business that sent the message. Account customers can contact us for platform-related requests.</p>
  <h2>8. Contact</h2><p>Privacy questions can be sent to <a href="mailto:privacy@whatstheup.in">privacy@whatstheup.in</a>. Data deletion steps are published on our <a href="/data-deletion">Data Deletion page</a>.</p>
</LegalPage>; }
