import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Building2, Plus, X } from 'lucide-react';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { api } from '../../services/api';
import type { AdminBusiness } from '../../types/admin';

const schema = z.object({
  businessName: z.string().trim().min(2, 'Enter the business name').max(190), ownerName: z.string().trim().min(2, 'Enter the owner name').max(190),
  ownerEmail: z.email('Enter a valid email'), ownerPassword: z.string().min(12, 'Use at least 12 characters'), timezone: z.string().min(1),
});
type Values = z.infer<typeof schema>;

export function AdminBusinessesPage() {
  const [creating, setCreating] = useState(false); const queryClient = useQueryClient();
  const query = useQuery({ queryKey: ['admin-businesses'], queryFn: async () => (await api.get<{ data: AdminBusiness[] }>('/admin/businesses')).data.data });
  const { register, handleSubmit, reset, formState: { errors } } = useForm<Values>({ resolver: zodResolver(schema), defaultValues: { timezone: 'Asia/Kolkata' } });
  const create = useMutation({ mutationFn: async (values: Values) => (await api.post<{ data: AdminBusiness }>('/admin/businesses', values)).data.data, onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['admin-businesses'] }); queryClient.invalidateQueries({ queryKey: ['admin-dashboard'] }); reset({ timezone: 'Asia/Kolkata' }); setCreating(false); } });
  const status = useMutation({ mutationFn: async ({ id, value }: { id: string; value: 'active' | 'suspended' }) => api.patch(`/admin/businesses/${id}`, { status: value }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['admin-businesses'] }); queryClient.invalidateQueries({ queryKey: ['admin-dashboard'] }); } });
  return <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-brand-700">Customers</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Businesses</h1><p className="mt-2 text-muted">Provision and control direct customer workspaces.</p></div><button onClick={() => setCreating(true)} className="flex items-center justify-center gap-2 rounded-xl bg-brand-700 px-4 py-3 text-sm font-semibold text-white hover:bg-brand-800"><Plus size={18}/> Create business</button></div>
    {creating && <section aria-label="Create business" className="mt-8 rounded-2xl border border-line bg-white p-6 shadow-card"><div className="flex items-start justify-between"><div><h2 className="text-xl font-semibold">Create customer business</h2><p className="mt-1 text-sm text-muted">Creates an active workspace and its first Business Owner.</p></div><button aria-label="Close form" onClick={() => setCreating(false)} className="rounded-lg p-2 hover:bg-gray-100"><X/></button></div><form className="mt-6 grid gap-5 md:grid-cols-2" onSubmit={handleSubmit((values) => create.mutate(values))}><Field label="Business name" error={errors.businessName?.message}><input className="input" {...register('businessName')}/></Field><Field label="Timezone" error={errors.timezone?.message}><select className="input" {...register('timezone')}><option value="Asia/Kolkata">Asia/Kolkata</option><option value="UTC">UTC</option><option value="Asia/Dubai">Asia/Dubai</option><option value="Europe/London">Europe/London</option><option value="America/New_York">America/New_York</option></select></Field><Field label="Owner name" error={errors.ownerName?.message}><input className="input" {...register('ownerName')}/></Field><Field label="Owner email" error={errors.ownerEmail?.message}><input type="email" className="input" {...register('ownerEmail')}/></Field><Field label="Temporary owner password" error={errors.ownerPassword?.message}><input type="password" autoComplete="new-password" className="input" {...register('ownerPassword')}/></Field><div className="flex items-end"><button disabled={create.isPending} className="w-full rounded-xl bg-brand-700 px-4 py-3 font-semibold text-white disabled:opacity-60">{create.isPending ? 'Creating…' : 'Create business and owner'}</button></div>{create.isError && <div role="alert" className="md:col-span-2 rounded-xl bg-red-50 p-3 text-sm text-red-700">{apiError(create.error)}</div>}</form></section>}
    <section className="mt-8 overflow-hidden rounded-2xl border border-line bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-gray-50 text-xs uppercase tracking-wide text-muted"><tr><th className="px-5 py-3">Business</th><th className="px-5 py-3">Owner</th><th className="px-5 py-3">Users</th><th className="px-5 py-3">Timezone</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-line">{query.data?.map((business) => <tr key={business.id}><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="rounded-xl bg-brand-50 p-2 text-brand-700"><Building2 size={18}/></span><div><p className="font-medium">{business.name}</p><p className="text-xs text-muted">{business.slug}</p></div></div></td><td className="px-5 py-4"><p>{business.ownerName ?? 'Not assigned'}</p><p className="text-xs text-muted">{business.ownerEmail}</p></td><td className="px-5 py-4">{business.userCount}</td><td className="px-5 py-4">{business.timezone}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-medium capitalize ${business.status === 'active' ? 'bg-brand-50 text-brand-700' : 'bg-amber-50 text-amber-700'}`}>{business.status}</span></td><td className="px-5 py-4 text-right"><button disabled={status.isPending} onClick={() => status.mutate({ id: business.id, value: business.status === 'active' ? 'suspended' : 'active' })} className="rounded-lg border border-line px-3 py-2 text-xs font-semibold hover:bg-gray-50">{business.status === 'active' ? 'Suspend' : 'Activate'}</button></td></tr>)}</tbody></table></div>{query.isLoading && <p className="p-8 text-center text-muted">Loading businesses…</p>}{!query.isLoading && query.data?.length === 0 && <p className="p-8 text-center text-muted">No businesses yet. Create the first customer workspace.</p>}</section>
  </div>;
}

function Field({ label, error, children }: { label: string; error: string | undefined; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block text-sm font-medium">{label}</span>{children}{error && <span className="mt-1 block text-sm text-red-600">{error}</span>}</label>; }
function apiError(error: Error): string { const candidate = error as Error & { response?: { data?: { error?: { message?: string } } } }; return candidate.response?.data?.error?.message ?? 'The business could not be created.'; }
