import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ClipboardPaste, FileUp, FolderPlus, UserPlus, Users } from 'lucide-react';
import { useRef, useState } from 'react';
import { api } from '../../services/api';
import type { ContactsResponse } from '../../types/operations';

type ImportRow = { name?: string; phone?: string; email?: string; tags?: string; consent?: string };
type ImportResult = { importedRows: number; updatedRows: number; skippedRows: number; errors?: { row: number; message: string }[] };

export function ContactsPage() {
  const input = useRef<HTMLInputElement>(null); const queryClient = useQueryClient(); const [preview, setPreview] = useState<ImportRow[]>([]); const [fileName, setFileName] = useState(''); const [selected, setSelected] = useState<string[]>([]); const [groupName, setGroupName] = useState(''); const [showGroupForm, setShowGroupForm] = useState(false); const [showManual, setShowManual] = useState(false); const [showPaste, setShowPaste] = useState(false); const [pasteValue, setPasteValue] = useState('');
  const query = useQuery({ queryKey: ['contacts'], queryFn: async () => (await api.get<{ data: ContactsResponse }>('/contacts')).data.data });
  const upload = useMutation({ mutationFn: async () => (await api.post('/contacts/import', { fileName, rows: preview })).data.data, onSuccess: () => { setPreview([]); setFileName(''); queryClient.invalidateQueries({ queryKey: ['contacts'] }); queryClient.invalidateQueries({ queryKey: ['dashboard'] }); } });
  const createGroup = useMutation({ mutationFn: async () => (await api.post('/contact-groups', { name: groupName, contactIds: selected })).data.data, onSuccess: () => { setGroupName(''); setSelected([]); setShowGroupForm(false); queryClient.invalidateQueries({ queryKey: ['contacts'] }); queryClient.invalidateQueries({ queryKey: ['contact-groups'] }); } });
  const addContacts = useMutation({ mutationFn: async ({ rows, source, fileName: importFile }: { rows: ImportRow[]; source: 'manual' | 'paste'; fileName: string }) => (await api.post<{ data: ImportResult }>('/contacts/import', { rows, source, fileName: importFile })).data.data, onSuccess: (result) => { const counts = `${result.importedRows} added · ${result.updatedRows} updated · ${result.skippedRows} skipped`; const detail = result.errors?.[0]?.message; const nothingSaved = result.importedRows + result.updatedRows === 0; window.alert(`${counts}${detail ? `\n${detail}` : ''}`); if (!nothingSaved) { setPasteValue(''); setShowManual(false); setShowPaste(false); } queryClient.invalidateQueries({ queryKey: ['contacts'] }); queryClient.invalidateQueries({ queryKey: ['dashboard'] }); } });
  const readCsv = (file: File) => { const reader = new FileReader(); reader.onload = () => { const lines = String(reader.result).replace(/^\uFEFF/, '').split(/\r?\n/).filter(Boolean); const [header, ...values] = lines; if (!header) return; const keys = parseCsvLine(header).map((key) => key.trim().toLowerCase()); const rows = values.map((line) => { const cells = parseCsvLine(line); return keys.reduce<ImportRow>((record, key, index) => ({ ...record, [key]: cells[index]?.trim() ?? '' }), {}); }).filter((row) => row.phone).slice(0, 5000); setFileName(file.name); setPreview(rows); }; reader.readAsText(file); };
  return <div className="space-y-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-brand-700">Audience</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Contacts</h1><p className="mt-2 text-muted">Import only people who have given you permission to receive WhatsApp messages.</p></div><div className="flex flex-wrap gap-2"><button onClick={() => setShowManual((value) => !value)} className="flex items-center justify-center gap-2 rounded-xl border border-line bg-white px-4 py-3 text-sm font-semibold"><UserPlus size={18}/> Add contact</button><button onClick={() => setShowPaste((value) => !value)} className="flex items-center justify-center gap-2 rounded-xl border border-line bg-white px-4 py-3 text-sm font-semibold"><ClipboardPaste size={18}/> Paste contacts</button><button onClick={() => input.current?.click()} className="flex items-center justify-center gap-2 rounded-xl bg-brand-700 px-4 py-3 text-sm font-semibold text-white"><FileUp size={18}/> Import CSV</button></div><input ref={input} className="hidden" type="file" accept=".csv,text/csv" onChange={(event) => { const file = event.target.files?.[0]; if (file) readCsv(file); event.currentTarget.value = ''; }}/></div>
    {showManual && <section className="rounded-2xl border border-line bg-white p-6"><h2 className="text-lg font-semibold">Add one contact</h2><p className="mt-1 text-sm text-muted">Phone numbers must include country code, e.g. +919876543210.</p><form className="mt-4 grid gap-3 md:grid-cols-2" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); addContacts.mutate({ source: 'manual', fileName: 'Manual contact', rows: [{ name: String(data.get('name') ?? ''), phone: String(data.get('phone') ?? ''), email: String(data.get('email') ?? ''), tags: String(data.get('tags') ?? ''), consent: String(data.get('consent') ?? 'opted_in') }] }); }}><input className="input" name="name" placeholder="Name"/><input className="input" name="phone" placeholder="+919876543210" required/><input className="input" name="email" type="email" placeholder="Email (optional)"/><input className="input" name="tags" placeholder="Tags, separated by commas"/><select className="input" name="consent" defaultValue="opted_in"><option value="opted_in">Opted in</option><option value="unknown">Consent unknown</option><option value="opted_out">Opted out</option></select><div className="flex gap-2"><button disabled={addContacts.isPending} className="rounded-xl bg-brand-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{addContacts.isPending ? 'Saving…' : 'Save contact'}</button><button type="button" onClick={() => setShowManual(false)} className="rounded-xl border border-line px-4 py-2.5 text-sm font-semibold">Cancel</button></div></form>{addContacts.isError && <p className="mt-3 text-sm text-red-700">{apiError(addContacts.error)}</p>}</section>}
    {showPaste && <section className="rounded-2xl border border-line bg-white p-6"><h2 className="text-lg font-semibold">Paste contacts</h2><p className="mt-1 text-sm text-muted">Paste one contact per line. Use just a phone number, or: Name, phone, email, tags, consent.</p><textarea className="input mt-4 min-h-40 font-mono text-sm" value={pasteValue} onChange={(event) => setPasteValue(event.target.value)} placeholder={'+919876543210\nAarav Sharma, +919876543211, aarav@example.com, new lead, opted_in\n+919876543212, Priya'}/><div className="mt-3 flex gap-2"><button disabled={addContacts.isPending || !parsePastedContacts(pasteValue).length} onClick={() => addContacts.mutate({ source: 'paste', fileName: 'Pasted contacts', rows: parsePastedContacts(pasteValue) })} className="rounded-xl bg-brand-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{addContacts.isPending ? 'Adding…' : `Add ${parsePastedContacts(pasteValue).length || ''} contacts`}</button><button onClick={() => setShowPaste(false)} className="rounded-xl border border-line px-4 py-2.5 text-sm font-semibold">Cancel</button></div>{addContacts.isError && <p className="mt-3 text-sm text-red-700">{apiError(addContacts.error)}</p>}</section>}
    {preview.length > 0 && <section className="rounded-2xl border border-brand-200 bg-brand-50 p-6"><h2 className="text-lg font-semibold">Ready to import {preview.length} contacts</h2><p className="mt-1 text-sm text-muted">Recognised columns: phone, name, email, tags and consent. Phone numbers must include the country code, for example +919876543210.</p><div className="mt-4 flex flex-wrap gap-3"><button disabled={upload.isPending} onClick={() => upload.mutate()} className="rounded-xl bg-brand-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{upload.isPending ? 'Importing…' : 'Confirm import'}</button><button onClick={() => { setPreview([]); setFileName(''); }} className="rounded-xl border border-line bg-white px-4 py-2.5 text-sm font-semibold">Cancel</button></div>{upload.isError && <p className="mt-3 text-sm text-red-700">{apiError(upload.error)}</p>}</section>}
    <section className="rounded-2xl border border-line bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Contact groups</h2><p className="mt-1 text-sm text-muted">Save audiences such as New leads, Repeat buyers or Mumbai customers.</p></div><button onClick={() => setShowGroupForm((value) => !value)} disabled={!selected.length} className="inline-flex items-center gap-2 rounded-xl border border-line px-3 py-2 text-sm font-semibold disabled:opacity-50"><FolderPlus size={16}/> Create group from {selected.length} selected</button></div>{showGroupForm && <div className="mt-4 flex flex-wrap gap-3 rounded-xl bg-brand-50 p-4"><input className="input max-w-sm bg-white" value={groupName} onChange={(event) => setGroupName(event.target.value)} placeholder="Group name, e.g. New leads" autoFocus/><button disabled={createGroup.isPending || groupName.trim().length < 2} onClick={() => createGroup.mutate()} className="rounded-xl bg-brand-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{createGroup.isPending ? 'Creating…' : 'Save group'}</button>{createGroup.isError && <p className="w-full text-sm text-red-700">{apiError(createGroup.error)}</p>}</div>}<div className="mt-4 flex flex-wrap gap-2">{query.data?.groups.length ? query.data.groups.map((group) => <div key={group.id} className="rounded-lg border border-brand-100 bg-brand-50 px-3 py-2 text-sm"><span className="font-semibold text-brand-800">{group.name}</span><span className="ml-2 text-brand-700">{group.memberCount} contacts</span></div>) : <p className="text-sm text-muted">Select contacts below to create your first reusable group.</p>}</div></section>
    <section className="overflow-hidden rounded-2xl border border-line bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-gray-50 text-xs uppercase tracking-wide text-muted"><tr><th className="w-12 px-5 py-3"><input aria-label="Select all contacts" type="checkbox" checked={!!query.data?.contacts.length && selected.length === query.data.contacts.length} onChange={(event) => setSelected(event.target.checked ? (query.data?.contacts.map((contact) => contact.id) ?? []) : [])}/></th><th className="px-5 py-3">Contact</th><th className="px-5 py-3">Phone</th><th className="px-5 py-3">Tags</th><th className="px-5 py-3">Consent</th><th className="px-5 py-3">Source</th></tr></thead><tbody className="divide-y divide-line">{query.data?.contacts.map((contact) => <tr key={contact.id}><td className="px-5 py-4"><input aria-label={`Select ${contact.name || contact.phone}`} type="checkbox" checked={selected.includes(contact.id)} onChange={(event) => setSelected((ids) => event.target.checked ? [...ids, contact.id] : ids.filter((id) => id !== contact.id))}/></td><td className="px-5 py-4"><p className="font-medium">{contact.name || 'Unnamed contact'}</p><p className="text-xs text-muted">{contact.email || '—'}</p></td><td className="px-5 py-4">{contact.phone}</td><td className="px-5 py-4">{contact.tags.length ? contact.tags.join(', ') : '—'}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${contact.consentStatus === 'opted_in' ? 'bg-brand-50 text-brand-700' : contact.consentStatus === 'opted_out' ? 'bg-red-50 text-red-700' : 'bg-gray-100 text-muted'}`}>{contact.consentStatus.replace('_', ' ')}</span></td><td className="px-5 py-4 capitalize text-muted">{contact.source}</td></tr>)}</tbody></table></div>{query.isLoading && <p className="p-8 text-center text-muted">Loading contacts…</p>}{!query.isLoading && !query.data?.contacts.length && <div className="p-12 text-center"><Users className="mx-auto text-brand-700"/><p className="mt-3 font-semibold">No contacts yet</p><p className="mt-1 text-sm text-muted">Import your opted-in audience to prepare your first campaign.</p></div>}</section>
    {query.data?.imports.length ? <section className="rounded-2xl border border-line bg-white p-6"><h2 className="font-semibold">Recent imports</h2><div className="mt-4 divide-y divide-line">{query.data.imports.map((item) => <div className="flex flex-wrap items-center justify-between gap-3 py-3 text-sm" key={item.id}><div><p className="font-medium">{item.fileName}</p><p className="text-muted">{item.importedRows} added · {item.updatedRows} updated · {item.skippedRows} skipped</p></div><span className="capitalize text-muted">{item.status.replaceAll('_', ' ')}</span></div>)}</div></section> : null}
  </div>;
}
function parseCsvLine(line: string): string[] { const cells: string[] = []; let value = ''; let quoted = false; for (let index = 0; index < line.length; index++) { const char = line[index]!; if (char === '"' && line[index + 1] === '"') { value += '"'; index++; } else if (char === '"') quoted = !quoted; else if (char === ',' && !quoted) { cells.push(value); value = ''; } else value += char; } cells.push(value); return cells; }
function parsePastedContacts(value: string): ImportRow[] { return value.split(/\r?\n/).map((line) => parseCsvLine(line).map((cell) => cell.trim())).filter((cells) => cells.some(Boolean)).map((cells) => { const first = cells[0] ?? ''; const second = cells[1] ?? ''; if (/^(\+|00)/.test(first)) return { phone: first, name: second, email: cells[2] ?? '', tags: cells[3] ?? '', consent: cells[4] ?? 'opted_in' }; return { name: first, phone: second, email: cells[2] ?? '', tags: cells[3] ?? '', consent: cells[4] ?? 'opted_in' }; }).filter((row) => !!row.phone).slice(0, 5000); }
function apiError(error: Error): string { const candidate = error as Error & { response?: { data?: { error?: { message?: string } } } }; return candidate.response?.data?.error?.message ?? 'Contacts could not be imported.'; }
