import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { FileUp, Users } from 'lucide-react';
import { useRef, useState } from 'react';
import { api } from '../../services/api';
import type { ContactsResponse } from '../../types/operations';

type ImportRow = { name?: string; phone?: string; email?: string; tags?: string; consent?: string };

export function ContactsPage() {
  const input = useRef<HTMLInputElement>(null); const queryClient = useQueryClient(); const [preview, setPreview] = useState<ImportRow[]>([]); const [fileName, setFileName] = useState('');
  const query = useQuery({ queryKey: ['contacts'], queryFn: async () => (await api.get<{ data: ContactsResponse }>('/contacts')).data.data });
  const upload = useMutation({ mutationFn: async () => (await api.post('/contacts/import', { fileName, rows: preview })).data.data, onSuccess: () => { setPreview([]); setFileName(''); queryClient.invalidateQueries({ queryKey: ['contacts'] }); queryClient.invalidateQueries({ queryKey: ['dashboard'] }); } });
  const readCsv = (file: File) => { const reader = new FileReader(); reader.onload = () => { const lines = String(reader.result).replace(/^\uFEFF/, '').split(/\r?\n/).filter(Boolean); const [header, ...values] = lines; if (!header) return; const keys = parseCsvLine(header).map((key) => key.trim().toLowerCase()); const rows = values.map((line) => { const cells = parseCsvLine(line); return keys.reduce<ImportRow>((record, key, index) => ({ ...record, [key]: cells[index]?.trim() ?? '' }), {}); }).filter((row) => row.phone).slice(0, 5000); setFileName(file.name); setPreview(rows); }; reader.readAsText(file); };
  return <div className="space-y-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-brand-700">Audience</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Contacts</h1><p className="mt-2 text-muted">Import only people who have given you permission to receive WhatsApp messages.</p></div><button onClick={() => input.current?.click()} className="flex items-center justify-center gap-2 rounded-xl bg-brand-700 px-4 py-3 text-sm font-semibold text-white"><FileUp size={18}/> Import CSV</button><input ref={input} className="hidden" type="file" accept=".csv,text/csv" onChange={(event) => { const file = event.target.files?.[0]; if (file) readCsv(file); event.currentTarget.value = ''; }}/></div>
    {preview.length > 0 && <section className="rounded-2xl border border-brand-200 bg-brand-50 p-6"><h2 className="text-lg font-semibold">Ready to import {preview.length} contacts</h2><p className="mt-1 text-sm text-muted">Recognised columns: phone, name, email, tags and consent. Phone numbers must include the country code, for example +919876543210.</p><div className="mt-4 flex flex-wrap gap-3"><button disabled={upload.isPending} onClick={() => upload.mutate()} className="rounded-xl bg-brand-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{upload.isPending ? 'Importing…' : 'Confirm import'}</button><button onClick={() => { setPreview([]); setFileName(''); }} className="rounded-xl border border-line bg-white px-4 py-2.5 text-sm font-semibold">Cancel</button></div>{upload.isError && <p className="mt-3 text-sm text-red-700">{apiError(upload.error)}</p>}</section>}
    <section className="overflow-hidden rounded-2xl border border-line bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-gray-50 text-xs uppercase tracking-wide text-muted"><tr><th className="px-5 py-3">Contact</th><th className="px-5 py-3">Phone</th><th className="px-5 py-3">Tags</th><th className="px-5 py-3">Consent</th><th className="px-5 py-3">Source</th></tr></thead><tbody className="divide-y divide-line">{query.data?.contacts.map((contact) => <tr key={contact.id}><td className="px-5 py-4"><p className="font-medium">{contact.name || 'Unnamed contact'}</p><p className="text-xs text-muted">{contact.email || '—'}</p></td><td className="px-5 py-4">{contact.phone}</td><td className="px-5 py-4">{contact.tags.length ? contact.tags.join(', ') : '—'}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${contact.consentStatus === 'opted_in' ? 'bg-brand-50 text-brand-700' : contact.consentStatus === 'opted_out' ? 'bg-red-50 text-red-700' : 'bg-gray-100 text-muted'}`}>{contact.consentStatus.replace('_', ' ')}</span></td><td className="px-5 py-4 capitalize text-muted">{contact.source}</td></tr>)}</tbody></table></div>{query.isLoading && <p className="p-8 text-center text-muted">Loading contacts…</p>}{!query.isLoading && !query.data?.contacts.length && <div className="p-12 text-center"><Users className="mx-auto text-brand-700"/><p className="mt-3 font-semibold">No contacts yet</p><p className="mt-1 text-sm text-muted">Import your opted-in audience to prepare your first campaign.</p></div>}</section>
    {query.data?.imports.length ? <section className="rounded-2xl border border-line bg-white p-6"><h2 className="font-semibold">Recent imports</h2><div className="mt-4 divide-y divide-line">{query.data.imports.map((item) => <div className="flex flex-wrap items-center justify-between gap-3 py-3 text-sm" key={item.id}><div><p className="font-medium">{item.fileName}</p><p className="text-muted">{item.importedRows} added · {item.updatedRows} updated · {item.skippedRows} skipped</p></div><span className="capitalize text-muted">{item.status.replaceAll('_', ' ')}</span></div>)}</div></section> : null}
  </div>;
}
function parseCsvLine(line: string): string[] { const cells: string[] = []; let value = ''; let quoted = false; for (let index = 0; index < line.length; index++) { const char = line[index]!; if (char === '"' && line[index + 1] === '"') { value += '"'; index++; } else if (char === '"') quoted = !quoted; else if (char === ',' && !quoted) { cells.push(value); value = ''; } else value += char; } cells.push(value); return cells; }
function apiError(error: Error): string { const candidate = error as Error & { response?: { data?: { error?: { message?: string } } } }; return candidate.response?.data?.error?.message ?? 'Contacts could not be imported.'; }
