import type { Metadata } from "next";
import { LegalPage } from "../site-components";
export const metadata: Metadata = { title: "Data Deletion Instructions | WhatstheUp", description: "How to request deletion of WhatstheUp account and platform data." };
export default function DataDeletion() { return <LegalPage eyebrow="Meta compliance" title="Data Deletion Instructions" intro="You can request deletion of information associated with your WhatstheUp account or a connected Meta account.">
  <h2>How to submit a request</h2><ol><li>Email <a href="mailto:privacy@whatstheup.in?subject=Data%20Deletion%20Request">privacy@whatstheup.in</a> with the subject “Data Deletion Request”.</li><li>Include your account email, business name and—if relevant—the Meta Business or WhatsApp Business Account ID. Do not send passwords or access tokens.</li><li>We will verify that you are authorised to act for the account before processing the request.</li></ol>
  <h2>What happens next</h2><p>After verification, we will close or de-identify the applicable account data and remove stored Meta credentials, contacts, campaign content and operational records that are no longer required. We may retain limited security, billing, audit or legal records where required or reasonably necessary.</p>
  <h2>Message recipients</h2><p>If you received a WhatsApp message from one of our customer businesses, contact that business first because it controls the contact and consent record. You can also email us with the sender’s business name and your phone number so we can route the request securely.</p>
  <h2>Meta account removal</h2><p>Removing WhatstheUp does not automatically delete information held independently by Meta. You may also need to remove the app or business integration from your Meta settings and submit any separate request required by Meta.</p>
  <div className="legal-callout"><h3>Need help?</h3><p>Email <a href="mailto:privacy@whatstheup.in">privacy@whatstheup.in</a>. We will provide a request reference after identity and authority checks are complete.</p></div>
</LegalPage>; }
