import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { FilePlus2, RefreshCw, X } from 'lucide-react';
import { useState } from 'react';
import { api } from '../../services/api';
import type { MessageTemplate } from '../../types/operations';

export function TemplatesPage() {
  const [creating, setCreating] = useState(false); const queryClient = useQueryClient();
  const query = useQuery({ queryKey: ['templates'], queryFn: async () => (await api.get<{ data: MessageTemplate[] }>('/templates')).data.data });
  const sync = useMutation({ mutationFn: async () => (await api.post('/meta/templates/sync')).data.data, onSuccess: () => queryClient.invalidateQueries({ queryKey: ['templates'] }) });
  const create = useMutation({ mutationFn: async (form: HTMLFormElement) => { const data = new FormData(form); const image = data.get('headerImage'); const headerImage = image instanceof File && image.size ? await fileToDataUrl(image) : ''; return (await api.post('/templates', { name: data.get('name'), language: data.get('language'), category: data.get('category'), body: data.get('body'), headerImage })).data.data; }, onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['templates'] }); setCreating(false); } });
  return <div className="space-y-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-brand-700">Message library</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Templates</h1><p className="mt-2 text-muted">Build compliant WhatsApp message drafts before you submit or sync them with Meta.</p></div><div className="flex flex-wrap gap-3"><button disabled={sync.isPending} onClick={() => sync.mutate()} className="flex items-center justify-center gap-2 rounded-xl border border-line bg-white px-4 py-3 text-sm font-semibold disabled:opacity-50"><RefreshCw size={18} className={sync.isPending ? 'animate-spin' : ''}/>{sync.isPending ? 'Syncing…' : 'Sync from Meta'}</button><button onClick={() => setCreating(true)} className="flex items-center justify-center gap-2 rounded-xl bg-brand-700 px-4 py-3 text-sm font-semibold text-white"><FilePlus2 size={18}/> New template</button></div></div>{sync.isError && <p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{apiError(sync.error)}</p>}
    {creating && <section className="rounded-2xl border border-line bg-white p-6 shadow-card"><div className="flex items-start justify-between"><div><h2 className="text-xl font-semibold">Create template draft</h2><p className="mt-1 text-sm text-muted">Use lowercase letters, numbers and underscores in the template name.</p></div><button aria-label="Close form" onClick={() => setCreating(false)} className="rounded-lg p-2 hover:bg-gray-100"><X/></button></div><form className="mt-5 grid gap-4 md:grid-cols-2" onSubmit={(event) => { event.preventDefault(); create.mutate(event.currentTarget); }}><Field label="Template name"><input className="input" name="name" placeholder="festival_offer" required/></Field><Field label="Category"><select className="input" name="category" defaultValue="marketing"><option value="marketing">Marketing</option><option value="utility">Utility</option><option value="authentication">Authentication</option></select></Field><Field label="Language"><select className="input" name="language" defaultValue="en_US"><option value="en_US">English (US)</option><option value="en_IN">English (India)</option><option value="hi_IN">Hindi</option></select></Field><Field label="Image header (optional)"><input className="input" name="headerImage" type="file" accept="image/jpeg,image/png,image/webp"/><span className="mt-1 block text-xs text-muted">JPEG, PNG or WebP, maximum 5 MB.</span></Field><Field label="Message body"><textarea className="input min-h-28" name="body" placeholder="Hello {{1}}, your update is ready." required/></Field><div className="md:col-span-2 flex gap-3"><button disabled={create.isPending} className="rounded-xl bg-brand-700 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">{create.isPending ? 'Saving…' : 'Save draft'}</button><button type="button" onClick={() => setCreating(false)} className="rounded-xl border border-line px-4 py-3 text-sm font-semibold">Cancel</button></div>{create.isError && <p className="md:col-span-2 text-sm text-red-700">{apiError(create.error)}</p>}</form></section>}
    <section className="grid gap-4 lg:grid-cols-2">{query.data?.map((template) => <article className="rounded-2xl border border-line bg-white p-6 shadow-card" key={template.id}><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{template.name}</p><p className="mt-1 text-xs text-muted">{template.category} · {template.language}</p></div><Status status={template.status}/></div><p className="mt-5 whitespace-pre-wrap text-sm leading-6 text-ink">{template.body}</p>{template.status === 'draft' && <p className="mt-5 rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-800">Draft only. Sync or submit it to Meta and wait for approval before it can be used in a live campaign.</p>}{template.rejectionReason && <p className="mt-4 text-sm text-red-700">{template.rejectionReason}</p>}</article>)}</section>{query.isLoading && <p className="text-center text-muted">Loading templates…</p>}{!query.isLoading && !query.data?.length && <section className="rounded-2xl border border-dashed border-line bg-white p-12 text-center"><p className="font-semibold">No templates yet</p><p className="mt-2 text-sm text-muted">Create a draft now, then have Meta approve it before sending.</p></section>}
  </div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block text-sm font-medium">{label}</span>{children}</label>; }
function Status({ status }: { status: MessageTemplate['status'] }) { return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold capitalize ${status === 'approved' ? 'bg-brand-50 text-brand-700' : status === 'rejected' ? 'bg-red-50 text-red-700' : 'bg-amber-50 text-amber-800'}`}>{status}</span>; }
function apiError(error: Error): string { const candidate = error as Error & { response?: { data?: { error?: { message?: string } } } }; return candidate.response?.data?.error?.message ?? 'The template could not be saved.'; }
function fileToDataUrl(file: File): Promise<string> { if (file.size > 5 * 1024 * 1024) return Promise.reject(new Error('The image must be no larger than 5 MB.')); return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error('The image could not be read.')); reader.readAsDataURL(file); }); }
