import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Megaphone, Plus, Send, X } from 'lucide-react';
import { useState } from 'react';
import { api } from '../../services/api';
import type { Campaign, ContactsResponse, MessageTemplate } from '../../types/operations';

export function CampaignsPage() {
  const [creating, setCreating] = useState(false); const queryClient = useQueryClient();
  const campaigns = useQuery({ queryKey: ['campaigns'], queryFn: async () => (await api.get<{ data: Campaign[] }>('/campaigns')).data.data });
  const templates = useQuery({ queryKey: ['templates'], queryFn: async () => (await api.get<{ data: MessageTemplate[] }>('/templates')).data.data });
  const contacts = useQuery({ queryKey: ['contacts'], queryFn: async () => (await api.get<{ data: ContactsResponse }>('/contacts')).data.data });
  const create = useMutation({ mutationFn: async (form: HTMLFormElement) => { const data = new FormData(form); const audienceType = String(data.get('audienceType')); const contactIds = audienceType === 'selected' ? data.getAll('contactIds').map(String) : []; return (await api.post('/campaigns', { name: data.get('name'), templateId: data.get('templateId'), audienceType, contactIds, scheduledAt: data.get('scheduledAt') || null })).data.data; }, onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['campaigns'] }); setCreating(false); } });
  const launch = useMutation({ mutationFn: async (id: string) => (await api.post(`/campaigns/${id}/launch`)).data.data, onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['campaigns'] }); queryClient.invalidateQueries({ queryKey: ['dashboard'] }); } });
  const approvedTemplates = templates.data?.filter((template) => template.status === 'approved') ?? []; const optedIn = contacts.data?.contacts.filter((contact) => contact.consentStatus === 'opted_in') ?? [];
  return <div className="space-y-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-brand-700">Campaign delivery</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Campaigns</h1><p className="mt-2 text-muted">Create a recipient snapshot, then launch only with a connected Meta account and an approved template.</p></div><button onClick={() => setCreating(true)} className="flex items-center justify-center gap-2 rounded-xl bg-brand-700 px-4 py-3 text-sm font-semibold text-white"><Plus size={18}/> Create campaign</button></div>
    {creating && <section className="rounded-2xl border border-line bg-white p-6 shadow-card"><div className="flex items-start justify-between"><div><h2 className="text-xl font-semibold">Create campaign</h2><p className="mt-1 text-sm text-muted">Only opted-in contacts are added to the audience.</p></div><button aria-label="Close form" onClick={() => setCreating(false)} className="rounded-lg p-2 hover:bg-gray-100"><X/></button></div><form className="mt-5 grid gap-4 md:grid-cols-2" onSubmit={(event) => { event.preventDefault(); create.mutate(event.currentTarget); }}><Field label="Campaign name"><input className="input" name="name" placeholder="Monsoon follow-up" required/></Field><Field label="Approved Meta template"><select className="input" name="templateId" required defaultValue=""><option value="" disabled>{approvedTemplates.length ? 'Select a template' : 'No approved templates available'}</option>{approvedTemplates.map((template) => <option key={template.id} value={template.id}>{template.name} · {template.language}</option>)}</select></Field><Field label="Audience"><select className="input" name="audienceType" defaultValue="all_opted_in"><option value="all_opted_in">All opted-in contacts ({optedIn.length})</option><option value="selected">Selected opted-in contacts</option></select></Field><Field label="Schedule (optional, UTC)"><input className="input" type="datetime-local" name="scheduledAt"/></Field><div className="md:col-span-2 rounded-xl border border-line p-4"><p className="text-sm font-semibold">Selected audience</p><p className="mt-1 text-xs text-muted">Choose contacts here only if you selected “Selected opted-in contacts” above.</p><div className="mt-3 max-h-40 space-y-2 overflow-auto">{optedIn.map((contact) => <label className="flex items-center gap-2 text-sm" key={contact.id}><input name="contactIds" type="checkbox" value={contact.id}/><span>{contact.name || contact.phone} <span className="text-muted">{contact.phone}</span></span></label>)}</div></div><div className="md:col-span-2 flex gap-3"><button disabled={create.isPending || !approvedTemplates.length} className="rounded-xl bg-brand-700 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">{create.isPending ? 'Creating…' : 'Create campaign draft'}</button><button type="button" onClick={() => setCreating(false)} className="rounded-xl border border-line px-4 py-3 text-sm font-semibold">Cancel</button></div>{create.isError && <p className="md:col-span-2 text-sm text-red-700">{apiError(create.error)}</p>}</form></section>}
    <section className="overflow-hidden rounded-2xl border border-line bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[920px] text-left text-sm"><thead className="bg-gray-50 text-xs uppercase tracking-wide text-muted"><tr><th className="px-5 py-3">Campaign</th><th className="px-5 py-3">Template</th><th className="px-5 py-3">Recipients</th><th className="px-5 py-3">Delivery</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-line">{campaigns.data?.map((campaign) => <tr key={campaign.id}><td className="px-5 py-4"><p className="font-medium">{campaign.name}</p><p className="text-xs text-muted">{campaign.scheduledAt ? `Scheduled: ${campaign.scheduledAt}` : 'Send when ready'}</p></td><td className="px-5 py-4">{campaign.templateName}<p className="text-xs text-muted">{campaign.templateLanguage}</p></td><td className="px-5 py-4">{campaign.recipientCount}</td><td className="px-5 py-4">{campaign.deliveredCount} delivered · {campaign.readCount} read</td><td className="px-5 py-4"><Status value={campaign.status}/></td><td className="px-5 py-4 text-right">{campaign.status === 'draft' ? <button disabled={launch.isPending} onClick={() => launch.mutate(campaign.id)} className="inline-flex items-center gap-1 rounded-lg bg-brand-700 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50"><Send size={14}/> Launch</button> : '—'}</td></tr>)}</tbody></table></div>{campaigns.isLoading && <p className="p-8 text-center text-muted">Loading campaigns…</p>}{!campaigns.isLoading && !campaigns.data?.length && <div className="p-12 text-center"><Megaphone className="mx-auto text-brand-700"/><p className="mt-3 font-semibold">No campaigns yet</p><p className="mt-1 text-sm text-muted">Import opted-in contacts and select an approved Meta template to get started.</p></div>}</section>{launch.isError && <p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{apiError(launch.error)}</p>}
  </div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block text-sm font-medium">{label}</span>{children}</label>; }
function Status({ value }: { value: string }) { return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold capitalize ${['queued', 'completed'].includes(value) ? 'bg-brand-50 text-brand-700' : value === 'draft' ? 'bg-gray-100 text-muted' : 'bg-amber-50 text-amber-800'}`}>{value}</span>; }
function apiError(error: Error): string { const candidate = error as Error & { response?: { data?: { error?: { message?: string } } } }; return candidate.response?.data?.error?.message ?? 'The campaign could not be completed.'; }
